### PR TITLE
Fix broken ascend update

### LINKED ISSUE #227: Change of style from e.g. solo to botch generates an invalid database entry
If a tour book entry e.g. with style _Solo_ is added and after saving, the style is changed to e.g. _Gesackt_, the entry is still coloured like a lead ascend (if enabled). It looks like there are two entries in the database because the entry can be deleted but the "eye" symbol is still there and shows an empty entry. The app crashes, if the delete button is pressed in the empty entry.
This doe not happen, if an entry is changed from e.g. _Solo_ to _Nachstieg_.

### PR DESCRIPTION
**Pull request by paetz**
Resolves #227

### CODE REVIEW

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt [hunk 1]
```diff
@@ -58,17 +59,22 @@ class AscendActivity : AppCompatActivity() {
 
         // The database query is different from null,
         // if this activity is called from the TourbookActivity or TourbookAscendActivity.
```
Comment (chrgernoe) [inline app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt:61]: This comment is not correct. This activity is only called from `TourbookAscendActivity`. right?

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt [hunk 2]
```diff
@@ -58,17 +59,22 @@ class AscendActivity : AppCompatActivity() {
...
+        _ascend = Ascend().apply {
+                    id = _outdatedAscend?.id ?: 0
+                    routeId = _outdatedAscend?.routeId ?: _route!!.id
+                    styleId = _outdatedAscend?.styleId ?: 0
+                    year = _outdatedAscend?.year ?: 0
+                    month = _outdatedAscend?.month ?: 0
+                    day = _outdatedAscend?.day ?: 0
+                    partnerIds = _outdatedAscend?.partnerIds ?: ArrayList()
+                    notes = _outdatedAscend?.notes ?: ""
+                }
```
Comment (chrgernoe) [inline app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt:77]: You initialize all properties again, however the `Ascend` class does it already for some of them. I think a more consistent way would be to do it for just the required ones.

What returns `_route!!.id`, if `_route` is `null`?

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt (hunk 1 above)
Comment (paetz) [reply app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt:61]: Correct but this comment is actually from you :)

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt (hunk 2 above)
Comment (paetz) [reply app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt:77]: 1. `_route` can only be `null` if `_outdatedAscend` is not `null`. So no problem here: However, I guess it's again time to have some unit tests :)
2. Yes, this initialization of `_ascend` is needed because I want to copy `_outdatedAscend` and there is no `copy` method in Kotlin for non-`data`-classes

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt (hunk 1 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt]: OK, I fixed it.
