### PR TITLE
Fix reset of rock and route ascends bit mask while tourbook import

### LINKED ISSUE #121: Tourbook import does not overwrite everything
If you import a tourbook where an entry already exists, a tourbook import should overwrite everything. However, the result is that this entry partly exists after the import. The summit and route is marked, you can select the eye symbol to show the entry but it is empty. If you try to delete this entry, the app crashes. You can work around this issue by adding a new tourbook entry for the same route and delete this entry immediatially.

Found in version `dev-20200222`.

### PR DESCRIPTION
**Pull request by chrgernoe**
Fix #121

### CODE REVIEW

File: app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt [hunk 1]
```diff
@@ -92,10 +92,10 @@ abstract class AppDatabase : RoomDatabase() {
 
     fun deleteAscends() {
         for (rock in rockDao().all) {
-            rock.ascendsBitMask = 0
+            rockDao().setAscendsBitMask(bitMask = 0, id = rock.id)
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt]: Haha, what a mistake :D Thx for fixing
