### PR TITLE
Fix disappearing partner selection, if search field is used

### LINKED ISSUE #224: Partner selection gets lost, if partner search  field is used
If the user selects one or more partners in the tour book entry dialog and then uses the partner search field, the previous selection gets lost.

### PR DESCRIPTION
**Pull request by chrgernoe**
Fixes #224

### CODE REVIEW

File: app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt [hunk 1]
```diff
@@ -207,25 +193,52 @@ class PartnersActivity : AppCompatActivity() {
...
+            view
+        }
+        val builder = AlertDialog.Builder(this).apply {
+            setTitle(dialogTitle)
+            setView(view)
+            setNegativeButton(R.string.cancel) { dialog, _ -> dialog.dismiss()}
+            // Set to null. We override the onclick below.
+            setPositiveButton(R.string.ok, null)
         }
+        // This solution prevents that the dialog is closed automatically,
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt:217]: Thx for documenting this. It seems that closing the dialog after clicking on negative/positive button is default behavior? If so, why is there a `dialog.dismiss()` in `setNegativeButton`? Same for `deletePartner`dialog

**Review by paetz — APPROVED** [review]

File: app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt [hunk 2]
```diff
@@ -144,56 +133,53 @@ class PartnersActivity : AppCompatActivity() {
...
             val innerLayout = RelativeLayout(this)
             innerLayout.setBackgroundColor(Color.WHITE)
 
-            val checkBox = CheckBox(this)
-            checkBox.text = partnerName
-            if (_selectedPartnerIds.contains(partner.id)) {
-                checkBox.isChecked = true
+            CheckBox(this).let {
+                it.text = partner.name.orEmpty()
+                if (_selectedPartnerIds.contains(partner.id)) {
```
[the remark this answers is not in the document]
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt:141]: `false` seems to be the default value because I didn't change this particular code line and it worked before, too. However, the suggested solution is safer and needs only one code line.

File: app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt (hunk 1 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt:217]: You are right, We can skip this and just set the listener to `null`.
