### PR TITLE
Fixed display of rocks and routes in tourbook and ascend activities

### LINKED ISSUE #174: Rock name mash-up in tourbook and ascend activities
I forgot to split german and czech names for the mentioned activities

### PR DESCRIPTION
**Pull request by paetz**
Resolves #174 .

I added some small design clean-ups, too (Increasing padding for readability).

### CODE REVIEW

File: app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt [hunk 1]
```diff
@@ -74,50 +74,45 @@ class DescriptionActivity : TableActivity() {
                         getString(R.string.route_quality),
                         RouteComment.QUALITY_MAP[comment.qualityId].orEmpty(),
                         WidgetUtils.textFontSizeDp,
-                        View.OnClickListener { },
+                        { },
```
Comment (chrgernoe) [inline app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt:77]: Maybe you should define this as default argument to avoid repetitive code.

**Review by chrgernoe — APPROVED** [review]

File: app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt (hunk 1 above)
Comment (paetz) [reply app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt]: Done. Merging now...
