### PR TITLE
Fix app crash when display is turned to landscape format during tourbook edit or input

### LINKED ISSUE #503: App crashes when display is turned to landscape format during tourbook edit or entry

### PR DESCRIPTION
**Pull request by chrgernoe**
* Fixes actual null pointer exception
* Fix/Feature: Preserve user inputs when display mode is changed

Fixes #503

### CODE REVIEW

**Review by paetz — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt [hunk 1]
```diff
@@ -72,16 +72,19 @@ class AscendActivity : BaseActivity<ActivityAscendBinding>() {
...
-            styleId = _outdatedAscend?.styleId ?: 0,
-            year = _outdatedAscend?.year ?: 0,
-            month = _outdatedAscend?.month ?: 0,
-            day = _outdatedAscend?.day ?: 0,
-            partnerIds = _outdatedAscend?.partnerIds ?: ArrayList(),
-            notes = _outdatedAscend?.notes ?: ""
-        )
+        _ascend = savedInstanceState.let {
+            Ascend(
+                id = it?.getInt("ascend_id") ?: _outdatedAscend?.id ?: 0,
```
[the remark this answers is not in the document]
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt]: Thx for the feedback. With your trigger, I found a even more elegant implementation.

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt [hunk 2]
```diff
@@ -174,7 +186,7 @@ class AscendActivity : BaseActivity<ActivityAscendBinding>() {
             onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
                 override fun onItemSelected(
                     parent: AdapterView<*>,
-                    view: View,
+                    view: View?,
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt:189]: Why is this change necessary?

**Review by paetz — APPROVED** [review]

File: app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt (hunk 2 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt:189]: That was the actual reason of the null pointer exception. The `view` can be null, if the display is turned.
