### PR TITLE
Fix that shared preferences use description strings instead of unique keys

### LINKED ISSUE #453: Shared preferences uses description strings instead of unique keys
Currently some preferences are stored using the the UI description strings instead of defined keys. That means, if the strings are changed for some reasons, the settings are lost.

**Proposal:**
Use defined keys and implement code that migrates existing settings to the new structure.

### PR DESCRIPTION
**Pull request by chrgernoe**
* Fixes #453 
* Needs merge of #429 before.

### CODE REVIEW

**Comment by chrgernoe** [comment]
We should also make the naming in the code consistent. Currently there are two different wordings:
* settings
* preferences

The Android library uses the the word _preferences_.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt [hunk 1]
```diff
@@ -84,19 +86,92 @@ class LaunchActivity : AppCompatActivity() {
...
+                    Pair(R.string.pref_key_color_lead, R.color.pref_default_color_lead),
+            R.string.follow to
+                    Pair(R.string.pref_key_color_follow, R.color.pref_default_color_follow)
+        )
+        _customSettings.let {
+            it.edit().apply {
+                for ((oldResource, newResourcePair) in settingsResourceMap) {
+                    val oldKey = resources.getString(oldResource)
+                    val newKey = resources.getString(newResourcePair.first)
+                    Log.d("[PREF]", "Checking for deprecated key '$oldKey'.")
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:153]: I think, if we want to introduce logging, we should check for creating a real logger module or so. So I'm not sure if we should really introduce it as part of this PR.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt [hunk 2]
```diff
@@ -84,19 +86,92 @@ class LaunchActivity : AppCompatActivity() {
...
         } else {
             false
         }
     }
+
+    /**
+     * Check whether the settings need to be migrated or not.
+     */
+    private fun _checkForSettingsMigration() {
+        if (_customSettings.getInt(getString(R.string.pref_key_pref_version), 1) == 1) {
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:109]: Wouldn't it make more sense to check for the latest version? Otherwise, we would always need to remember adapting this line when we increase the version.

Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:109]: Wouldn't it make more sense to check for the latest version? Otherwise, we would always need to remember adapting this line when we increase the version.

Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:109]: Wouldn't it make more sense to check for the latest version? Otherwise, we would always need to remember adapting this line when we increase the version.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt [hunk 3]
```diff
@@ -84,19 +86,92 @@ class LaunchActivity : AppCompatActivity() {
...
+            _migrateSettings()
+        }
+    }
+
+    /**
+     * Migrate settings, if necessary, to fix issue https://github.com/YacGroup/yacguide/issues/453.
+     */
+    private fun _migrateSettings() {
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:117]: - [ ] All this migration stuff should not be part of `LaunchActivity`. Please move this functionality to a separate file.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt [hunk 4]
```diff
@@ -84,19 +86,92 @@ class LaunchActivity : AppCompatActivity() {
...
+        )
+        _customSettings.let {
+            it.edit().apply {
+                for ((oldResource, newResourcePair) in settingsResourceMap) {
+                    val oldKey = resources.getString(oldResource)
+                    val newKey = resources.getString(newResourcePair.first)
+                    Log.d("[PREF]", "Checking for deprecated key '$oldKey'.")
+                    if (it.contains(oldKey)) {
+                        Log.d("[PREF]", "Migrating key '$oldKey' to '$newKey'.")
+                        if (oldResource in listOf(R.string.lead, R.string.follow)) {
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:156]: Creating a new list by using `listOf` performs worse than `(oldResource == R.string.lead || oldResource == R.string.follow)`

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt (hunk 3 above)
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:117]: This migration stuff is quite critical. I would suggest to have a separate, unit-tested class for this.

File: app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt [hunk 5]
```diff
@@ -35,6 +35,7 @@ class SearchBarHandler(searchBarLayout: ConstraintLayout,
                        private val _checkBoxTitle: String = "",
```
Comment (paetz) [inline app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt:35]: I think, this can be a normal argument now, since it is only used in `init {}`?

**Review by paetz — CHANGES_REQUESTED** [review]

**Comment by paetz** [comment]
This is a quite critical change. I suggest to trigger a dev release after merging it to have some more time for testing.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt (hunk 1 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:153]: OK, I agree. It was mainly for debugging but I will remove it.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt (hunk 2 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:109]: Duplicated comment.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt (hunk 3 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt:117]: Makes sense. I'm going to implement a test for this.

File: app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt (hunk 2 above)
Comment (chrgernoe) [reply app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt]: Duplicated comment.

**Review by paetz — APPROVED** [review]
